# meta/main.yml

- name: DOTFILES | get dotfiles from git repository
  git: repo={{ dotfiles_repo_url }} dest="/tmp/dotfiles" accept_hostkey=yes
  register: dotfiles_downloaded
- name: DOTFILES | install dotfiles
  command: ./bootstrap.sh -f chdir="/tmp/dotfiles"
  become: yes
  become_user: {{ user }}
  when: dotfiles_downloaded.changed
