# meta/main.yml

- name: DOTFILES | get dotfiles from git repository
  git: repo={{ dotfiles_repo_url }} dest="/tmp/dotfiles" accept_hostkey=yes
  become: yes
  register: dotfiles_downloaded
- name: DOTFILES | install dotfiles
  command: "/tmp/dotfiles/bootstrap.sh -f"
  become: yes
  when: dotfiles_downloaded.changed
