# meta/main.yml

- name: DOTFILES | get dotfiles from git repository
  git: repo={{ dotfiles_repo_url }} dest={{ dotfiles_tmp }} accept_hostkey=yes
  sudo: False
  register: dotfiles_downloaded
- name: DOTFILES | install dotfiles
  command: "{{ dotfiles_tmp }}/bootstrap.sh -f -d {{ dotfiles_dest }}"
  sudo: False
  when: dotfiles_downloaded.changed and when {{ run_bootstrap }}
